# Generated by Django 4.0.6 on 2022-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='month',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('ADMIN', 'Admin')], default='REGULAR', max_length=10),
        ),
    ]
