# Generated by Django 4.0.6 on 2022-07-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_member_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='month',
            new_name='role',
        ),
    ]
