# Generated by Django 4.0.6 on 2022-07-26 05:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_month_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12503173027', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('REGULAR', "Regular - Can't delete members"), ('ADMIN', 'Admin - Can delete memebers')], default='REGULAR', max_length=10),
        ),
    ]
