# Generated by Django 4.0.6 on 2022-07-26 06:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_member_phone_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='first name', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='last name', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
