# Generated by Django 4.0.6 on 2022-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_member_first_name_alter_member_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
