# Generated by Django 4.0.6 on 2022-07-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_member_first_name_alter_member_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Regular', "Regular - Can't delete members"), ('Admin', 'Admin - Can delete memebers')], default='Regular', max_length=10),
        ),
    ]
